[package]
name = "note"
version = "0.1.0"
authors = ["Sean Walsh <sean@swalsh.org>"]

[dependencies]
docopt = "1"
serde = "1.0"
serde_derive = "1.0"
termion = "1.0"
text_io = "0.1.7"
time = "0.1.40"

[dependencies.rusqlite]
version = "0.13.0"
features = ["bundled"]
